services:
  custom-db:
    image: custom-postgres:17.5-0.1
    build:
      context: .
      dockerfile: db-dockerfiles/Dockerfile
    environment:
      POSTGRES_USER: user1
      POSTGRES_PASSWORD: password1
    develop:
      watch:
        - action: rebuild
          path: ./db
          target: /docker-entrypoint-initdb.d
        - action: rebuild
          path: db-dockerfiles

  adminer:
    image: adminer
    environment:
      - ADMINER_DEFAULT_SERVER=custom-db
    ports:
      - "8080:8080"
